### PR TITLE
Ensure changes in ANGULAR_SRC folder sync to Docker Container

### PR DESCRIPTION
**Pull request by tdonohue**
Minor change to `ang-src.override.yml` to ensure that any changes to the `$ANGULAR_SRC` folder sync to the Docker Container.  This allows developers to change their local folder, and (within a minute or two) see those changes on the running Docker container.

How to test:
* Ensure you have `$ANGULAR_SRC` defined locally to point at a local checkout of https://github.com/DSpace/dspace-angular
* Build your local checkout as a Docker container: `docker-compose -p d7 -f docker-compose.yml -f d7.override.yml -f load.entities.yml -f ang-src.override.yml build`
* Spin up that container in Docker: `docker-compose -p d7 -f docker-compose.yml -f d7.override.yml -f load.entities.yml -f ang-src.override.yml up -d`
* Now, make a local change to your `$ANGULAR_SRC` folder.  For example, change a font or tweak the color scheme.
* In a minute or two, your Docker container will pick up those changes, and will deploy them to your running container.  You can watch for the changes by running `docker logs dspace-angular -f`

Please note, unfortunately at this time, this only works for the FIRST change (not any further changes) until we merge this related dspace-angular PR: https://github.com/DSpace/dspace-angular/pull/411   Once that related PR is merged, then webpack will pick up any changes and redeploy them to the running Docker container (without needing to restart Docker)

### CODE REVIEW

**Comment by terrywbrady** [comment]
@tdonohue , this looks good.  Should DSPACE_WEBPACK_POLLING be set in the override file per https://github.com/DSpace/dspace-angular/pull/411?

**Review by terrywbrady — APPROVED** [review]

**Comment by tdonohue** [comment]
@terrywbrady : yes, this PR won't work as well (at least on Windows host machine. which is the only place I tested) until we find a way to enable Webpack "polling" as described in https://github.com/DSpace/dspace-angular/pull/411

So, I like the idea of enabling Polling just for Docker (via an environment variable like DSPACE_WEBPACK_POLLING).  However, I haven't had a chance to look into how to achieve that quite yet.  If you find time to play around with this general idea, please feel free.  Otherwise, this may need to wait until I have time to get back to this again.

In the meantime, we could consider merging this PR.  But, we have to realize that it only seems to "sync" the first change to Docker, which obviously is not as useful.

**Review by terrywbrady — CHANGES_REQUESTED** [review]
I was able to confirm that the first change that I made in ANGULAR_SRC was adopted.

After further testing, my dspace-angular local image was unable to be restarted.  I began to see the following error.

```
$ yarn run clean:dist
$ rimraf dist
dspace-angular    | /app/node_modules/rimraf/bin.js:47
dspace-angular    |       throw er
dspace-angular    |       ^
dspace-angular    |
dspace-angular    | Error: ENOTEMPTY: directory not empty, rmdir 'dist'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about t
```

I wonder if there is a read/write permission error getting introduced in this process.  @tdonohue , could we take a closer look at this together?

**Comment by tdonohue** [comment]
Closing this PR as this repository is **deprecated**

**Pull request closed without merging**
