### PR TITLE
Load entities SQL on initial load

### PR DESCRIPTION
**Pull request by terrywbrady**
## Preparation

- Clone this repository
- Checkout this branch
- Download and unzip the entities SQL
  - https://www.dropbox.com/s/ovqp394y3vofnwa/entities7-test-db.sql.gz?dl=1
- export LOADSQL=<path to the sql file>
- cd to docker-compose-files/dspace-compose

## Run docker-compose to initialize the database

```
DSPACE_VER=entities ANGULAR_VER=entities docker-compose -p d7ent -f docker-compose.yml -f d7.override.yml -f load.entities.yml up -d
```

## Index the Content
Once the services have started up, index the data

```
docker exec -it dspace //dspace/bin/dspace index-discovery
```

## To stop the services

```
docker-compose -p d7ent -f docker-compose.yml -f d7.override.yml -f load.entities.yml down
```

## On subsequent restart, you do not need the load.entities.yml file

```
DSPACE_VER=entities ANGULAR_VER=entities docker-compose -p d7ent -f docker-compose.yml -f d7.override.yml up -d
```

Our recommended Docker installation instructions are here: https://dspace-labs.github.io/DSpace-Docker-Images/documentation/tutorialSetup.html

### CODE REVIEW

**Comment by terrywbrady** [comment]
@artlowel , Thanks.  I would like to create images to allow you to do the full end to end test.  Which branches should be built?

**Comment by tdonohue** [comment]
@terrywbrady : You should be able to use the `configurable_entities` branch both from DSpace/DSpace (REST API side) and from DSpace/dspace-angular (Angular side).  That branch exists in both projects, and is the base branch for the Configurable Entities PRs (https://github.com/DSpace/DSpace/pull/2376 and https://github.com/DSpace/dspace-angular/pull/372).

**Comment by terrywbrady** [comment]
@artlowel and @tdonohue , I published new docker images for the container_entities branches.  I made a small change to one yaml file.

I also updated the command in the PR documentation to reference these new images.

Give this a try and let me know if you see the features you expect to see.  I will home to do some additional testing of the new features.

**Comment by artlowel** [comment]
I tested it again. 

Now the container running the dspace/dspace:entities image seems to go down the first time you try to visit http://localhost:8080/spring-rest/api

I tried it on a different machine (also a mac, running the latest mojave), because I figured something from the previous test might have lingered and influenced the result, but I got the same issue both times.

**Comment by terrywbrady** [comment]
@artlowel ,

I am able to open spring-rest and I am able to browse with Angular.

```
$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                            NAMES
7e8f8c5af319        dspace/dspace-angular:entities    "/bin/sh -c 'yarn ru…"   17 hours ago        Up 17 hours         0.0.0.0:3000->3000/tcp, 0.0.0.0:9876->9876/tcp   dspace-angular
14e511580ddf        dspace/dspace:entities            "/dspace-docker-tool…"   17 hours ago        Up 17 hours         8009/tcp, 0.0.0.0:8080->8080/tcp                 dspace
222116be98c7        dspace/dspace-postgres-pgcrypto   "docker-entrypoint.s…"   17 hours ago        Up 17 hours         5432/tcp                                         dspacedb
```

If you had not seem the same error on 2 different machines, I would have suspected that you might need to recreate your Docker volumes.

When you run docker ps, do you see these same images in the listing?

**Comment by artlowel** [comment]
@terrywbrady No, `dspace/dspace:entities` drops out of that list as soon as I (or the angular client) try to access http://localhost:8080/spring-rest/api

**Comment by terrywbrady** [comment]
Thanks @artlowel .  I will merge this change.

I am going to log a new issue to document recommended memory allocations for users.

**Pull request merged**
